# Site Settings
title:               Kitson Swann
tagline:             my Data Science Blog
description:
url:                #"https://kitsonswann.github.io"
github:
  url:               "https://kitsonswann.github.io"
author:
  name:              "Kitson Swann"
  email:             "kptswann@gmail.com"
  twitter:           "seriousswann"
  instagram:         "seriousswann"
  github:            "kitsonswann"
  facebook:          "kitsonswann"
  linkedin:          "kitsonswann"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
